title: Sujay Bagi, PhD # your name (or website title) here
logo: "/images/Sujay1a.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/sujay-bagi/">View My LinkedIn Profile</a> <br>
  <a href="https://www.dropbox.com/scl/fi/lwnoj9eriuwp6gddp9u3r/Sujay-Bagi-Resume-MIT.pdf?rlkey=sa1r9tno7njuanbnjh1kzlpmv&st=ev0qeqjm&dl=0">View My Resume</a> <br>
  <a href="https://scholar.google.com/citations?user=ap8CUAcAAAAJ&hl=en&oi=ao">View My Google Scholar</a> <br>
  <a href="https://www.romangroup.mit.edu/">View My Research Lab</a>
  <br><br>
  I'm a Materials Scientist and a Mechanical Engineer at MIT. My background at the intersection of materials science, mechanical/chemical engineering positions me to understand and efficiently tackle real-world challenges in areas such as crystallization science, materials synthesis, carbon capture, energy storage, techno-economic modelling, automotive emissions, and renewable energy technologies. 
  <br>
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
